### ISSUE TITLE
Dati storici 

### ISSUE THREAD

**Issue by thecas89-teacher** [StefanoCasagrande/Vaccine_Stats#2]
La app é fatta bene ma per quanto mi riguarda avrebbe un senso 10 volte maggiore se lei implementa i dati storici per vedere l'andamento della campagna vaccinale.
Cosa che la dashboard ufficiale non fa.
Buon lavoro

**Comment by StefanoCasagrande** [comment]
Stavo inserendo la possibilità di vedere il numero medio di somministrazioni negli ultimi 7 giorni per calcolare le tempistiche necessarie per coprire la popolazione ma i dati effettivamente sono gli stessi e non dovrebbe essere complicato inserire anche un grafico con l'andamento... Ottimo idea, sì.

**Comment by thecas89-teacher** [comment]
Beh alla fine per i dati storici basta salvarli, per regione una volta al giorno di notte. Non so se utilizzi un backend tipo SQL o NOSQL, ma alla fine ti basta aggiungere un batch che te li tiri dentro.
Poi con le API che hai usato per fare i grafici regionali secondo me puoi riusare il codice.

**Comment by StefanoCasagrande** [comment]
![2021-03-14 01 07 09](https://user-images.githubusercontent.com/28094181/111062238-f634ea80-84a7-11eb-87c7-5eff98c60ee7.jpg)

Disponibile nella versione 1.0.4.1 ( in fase di revisione da parte di Google )

**Comment by thecas89-teacher** [comment]
Ottimo lavoro! Complimenti!
