### ISSUE TITLE
Somministrazioni per categoria su base regionale

### ISSUE THREAD

**Issue by escherstair** [StefanoCasagrande/Vaccine_Stats#3]
Complimenti per l'app, senza fronzoli e ben fatta.
Secondo me sarebbe utile potenziare un po' la sezione "Situazione per regione", aggiungendo anche le viste "somministrazione per categoria" e "somministrazione per età".
E magari, dare la possibilità di salvare una regione come "preferita".

**Comment by StefanoCasagrande** [comment]
![2021-03-14 11 52 52](https://user-images.githubusercontent.com/28094181/111065813-f0490480-84bb-11eb-817c-2dd0c5bb0d63.jpg)

![2021-03-14 11 53 06](https://user-images.githubusercontent.com/28094181/111065818-f7701280-84bb-11eb-95cf-c34f8a7a9e4e.jpg)

Da prossima versione aggiunta statistica per categoria su base regionale.
Sull'età ci sono delle limitazioni tecniche ( il ministero le fornisce solo in un file dettagliato di quasi 2 mega, diventa improponibile farlo scaricare ogni volta ).
Sul preferito faccio qualche valutazione e vedo se è gestibile senza aggiungere troppa confusione all'età finale..

Ti ringrazio per le annotazioni.

**Comment by escherstair** [comment]
Dopo l'aggiornamento della app, sul mio cellulare Xiaomi redmi 4 la app va
in crash all'avvio

Il dom 14 mar 2021, 11:58 Stefano Casagrande ***@***.***> ha
scritto:

**Comment by escherstair** [comment]
Questo il log

java.lang.RuntimeException: Unable to start activity
ComponentInfo{it.stefanocasagrande.vaccini_stats/it.stefanocasagrande.vaccini_stats.MainActivity}:
android.database.sqlite.SQLiteException: no such table: SOMMINISTRAZIONI
(code 1): , while compiling: DROP TABLE SOMMINISTRAZIONI
at
android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2723)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2784)
at android.app.ActivityThread.-wrap12(ActivityThread.java)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1523)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:163)
at android.app.ActivityThread.main(ActivityThread.java:6238)
at java.lang.reflect.Method.invoke(Native Method)
at
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:933)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:823)
Caused by: android.database.sqlite.SQLiteException: no such table:
SOMMINISTRAZIONI (code 1): , while compiling: DROP TABLE SOMMINISTRAZIONI
at android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native
Method)
at
android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:889)
at
android.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java:500)
at android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:588)
at android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java:58)
at android.database.sqlite.SQLiteStatement.<init>(SQLiteStatement.java:31)
at
android.database.sqlite.SQLiteDatabase.executeSql(SQLiteDatabase.java:1678)
at android.database.sqlite.SQLiteDatabase.execSQL(SQLiteDatabase.java:1608)
at it.stefanocasagrande.vaccini_stats.Common.DB.Check_Table(DB.java:59)
at
it.stefanocasagrande.vaccini_stats.MainActivity.onCreate(MainActivity.java:108)
at android.app.Activity.performCreate(Activity.java:6857)
at
android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1119)
at
android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2676)
... 9 more


Il mar 16 mar 2021, 18:21 Ernest ***@***.***> ha scritto:

**Comment by StefanoCasagrande** [comment]
A breve dovrebbe apparire una versione "open test" su PlayStore se vuoi provare.

**Comment by escherstair** [comment]
Non riesco a capire come scaricare la versione open test.
Tu mi sai aiutare?

Il mar 16 mar 2021, 19:13 Stefano Casagrande ***@***.***> ha
scritto:

**Comment by StefanoCasagrande** [comment]
> Non riesco a capire come scaricare la versione open test. Tu mi sai aiutare?

Se rimuovi e re-installi il problema dovrebbe risolversi da solo, è un problema che si presenta per chi aggiorna da 1.0.2 a 1.0.4.2

Si risolve con la 1.0.4.6 che dovrebb apparire su PlayStore temo non prima di domani..

**Comment by escherstair** [comment]
Disinstallata e reinstallata.
Tutto ok

Il mar 16 mar 2021, 19:54 Stefano Casagrande ***@***.***> ha
scritto:
