### ISSUE TITLE
app non piu utilizzabile dopo aggiornamento.

### ISSUE THREAD

**Issue by thecas89-teacher** [StefanoCasagrande/Vaccine_Stats#5]
Ciao, dalla versione che 1.0.4.2 che é andatw oggi sul pastore, l'app sul mio samsung a20 non parte più,  crasha dopo la barra di caricamento.

**Comment by StefanoCasagrande** [comment]
> Ciao, dalla versione che 1.0.4.2 che é andatw oggi sul pastore, l'app sul mio samsung a20 non parte più, crasha dopo la barra di caricamento.

Se rimuovi e re-installi il problema dovrebbe risolversi da solo, è un problema che si presenta per chi aggiorna da 1.0.2 a 1.0.4.2

Si risolve con la 1.0.4.6 che è già in revisione su PlayStore ma temo non verrà approvata da Google prima di domani..

**Comment by thecas89-teacher** [comment]
Ho visto, adesso funziona. Ti apro un altro ticket per una veloce correzione
