### ISSUE TITLE
Testo errato andamento vaccinale

### ISSUE THREAD

**Issue by thecas89-teacher** [StefanoCasagrande/Vaccine_Stats#6]
Nel nuovo grafico del numero di vaccinazioni del giorno il testo é errato, in quanto si scrive: Nel periodo indicato (XX giorni) sono state somministrate in media y vaccini al giorno.
L'errore é che all'utente viene restituita la somma delle vaccinazioni e non la media.

**Comment by StefanoCasagrande** [comment]
> Nel nuovo grafico del numero di vaccinazioni del giorno il testo é errato, in quanto si scrive: Nel periodo indicato (XX giorni) sono state somministrate in media y vaccini al giorno.
> L'errore é che all'utente viene restituita la somma delle vaccinazioni e non la media.

Già corretto nel commit 2dc763f7957ae13c1b5542a173ddca924853f35d

Fa la media dividendo per 7 ( una settimana ) anche se il periodo selezionato è diverso.
Si risolve anche quello con 1.0.4.6

Spiace per l'inconveniente ma ho voluto strafare inserendo troppe cose testando troppo poco :-(
