### ISSUE TITLE
Aggiornamento parziale dei dati

### ISSUE THREAD

**Issue by escherstair** [StefanoCasagrande/Vaccine_Stats#9]
Da alcuni giorni ho notato un comportamento strano della app:

- il grafico andamento vaccinazioni non consente di visualizzare una data successiva al 19/04/2021
- i numeri riportati nella situazione generale aumentano progressivamente, ma sono inferiori a quelli riportati dal repository ufficiale
- il grafico del dettaglio consegne ha cambiato colori e sembra che AstraZeneca e Moderna si sovrappongano parzialmente

Potrebbe essere tutto dovuto ad alcuni cambiamenti fatti recentemente nella struttura dati?
Nome Astra Zeneca cambiato, nuove categorie aggiunte, ...

**Comment by StefanoCasagrande** [comment]
Sì, è causato da quello ( nel Changelog.md l'hanno inserito solo il 20 aprile )

Avevo già commitato la soluzione il 21 aprile ma PlayStore ha tempi biblici per caricare gli aggiornamenti.
Dovrebbe essere disponibile anche su PlayStore la versione 1.0.5.9 che risolve a breve...
